[metadata]
creation_date = "2020/12/23"
maturity = "production"
updated_date = "2020/12/23"

[rule]
author = ["Elastic"]
description = """
Identifies the execution of Automator Workflows process. Adversaries may drop a custom workflow template that host
malicious JXA code as an alternative to using osascript.
"""
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "eql"
license = "Elastic License"
name = "Script Execution via Automator Workflows"
references = ["https://posts.specterops.io/persistent-jxa-66e1c3cd1cf5"]
risk_score = 47
rule_id = "5d9f8cfc-0d03-443e-a167-2b0597ce0965"
severity = "medium"
tags = ["Elastic", "Host", "macOS", "Threat Detection", "Execution"]
type = "eql"

query = '''
sequence by host.id with maxspan=30s
 [file where event.type in ("change", "creation") and file.extension == "wflow"]
 [process where event.type in ("start", "process_started") and process.name == "automator"]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"

