[metadata]
creation_date = "2021/01/04"
maturity = "development"
updated_date = "2021/01/04"

[rule]
author = ["Skoetting"]
description = """
Identifies attempts to create new local users. This is sometimes done by attackers to increase access to a system or
domain.
"""
index = ["winlogbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "User Account Creation Eventlogs"
risk_score = 21
rule_id = "38e17753-f581-4644-84da-0d60a8318694"
severity = "low"
tags = ["Elastic", "Host", "Windows", "Threat Detection", "Persistence"]
type = "query"

query = '''
event.module:"security" and event.code:4720
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1136"
name = "Create Account"
reference = "https://attack.mitre.org/techniques/T1136/"


[rule.threat.tactic]
id = "TA0003"
name = "Persistence"
reference = "https://attack.mitre.org/tactics/TA0003/"

